package me.rerere.material3

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import dynamiccolor.DynamicScheme

fun DynamicScheme.toColorScheme(): ColorScheme {
    return if (isDark) {
        darkColorScheme(
            primary = Color(getPrimary()),
            onPrimary = Color(getOnPrimary()),
            primaryContainer = Color(getPrimaryContainer()),
            onPrimaryContainer = Color(getOnPrimaryContainer()),
            inversePrimary = Color(getInversePrimary()),
            secondary = Color(getSecondary()),
            onSecondary = Color(getOnSecondary()),
            secondaryContainer = Color(getSecondaryContainer()),
            onSecondaryContainer = Color(getOnSecondaryContainer()),
            tertiary = Color(getTertiary()),
            onTertiary = Color(getOnTertiary()),
            tertiaryContainer = Color(getTertiaryContainer()),
            onTertiaryContainer = Color(getOnTertiaryContainer()),
            background = Color(getBackground()),
            onBackground = Color(getOnBackground()),
            surface = Color(getSurface()),
            onSurface = Color(getOnSurface()),
            surfaceVariant = Color(getSurfaceVariant()),
            onSurfaceVariant = Color(getOnSurfaceVariant()),
            surfaceTint = Color(getSurfaceTint()),
            inverseSurface = Color(getInverseSurface()),
            inverseOnSurface = Color(getInverseOnSurface()),
            error = Color(getError()),
            onError = Color(getOnError()),
            errorContainer = Color(getErrorContainer()),
            onErrorContainer = Color(getOnErrorContainer()),
            outline = Color(getOutline()),
            outlineVariant = Color(getOutlineVariant()),
            scrim = Color(getScrim()),
            surfaceBright = Color(getSurfaceBright()),
            surfaceDim = Color(getSurfaceDim()),
            surfaceContainer = Color(getSurfaceContainer()),
            surfaceContainerHigh = Color(getSurfaceContainerHigh()),
            surfaceContainerHighest = Color(getSurfaceContainerHighest()),
            surfaceContainerLow = Color(getSurfaceContainerLow()),
            surfaceContainerLowest = Color(getSurfaceContainerLowest()),
            primaryFixed = Color(getPrimaryFixed()),
            primaryFixedDim = Color(getPrimaryFixedDim()),
            onPrimaryFixed = Color(getOnPrimaryFixed()),
            onPrimaryFixedVariant = Color(getOnPrimaryFixedVariant()),
            secondaryFixed = Color(getSecondaryFixed()),
            secondaryFixedDim = Color(getSecondaryFixedDim()),
            onSecondaryFixed = Color(getOnSecondaryFixed()),
            onSecondaryFixedVariant = Color(getOnSecondaryFixedVariant()),
            tertiaryFixed = Color(getTertiaryFixed()),
            tertiaryFixedDim = Color(getTertiaryFixedDim()),
            onTertiaryFixed = Color(getOnTertiaryFixed()),
            onTertiaryFixedVariant = Color(getOnTertiaryFixedVariant()),
        )
    } else {
        lightColorScheme(
            primary = Color(getPrimary()),
            onPrimary = Color(getOnPrimary()),
            primaryContainer = Color(getPrimaryContainer()),
            onPrimaryContainer = Color(getOnPrimaryContainer()),
            inversePrimary = Color(getInversePrimary()),
            secondary = Color(getSecondary()),
            onSecondary = Color(getOnSecondary()),
            secondaryContainer = Color(getSecondaryContainer()),
            onSecondaryContainer = Color(getOnSecondaryContainer()),
            tertiary = Color(getTertiary()),
            onTertiary = Color(getOnTertiary()),
            tertiaryContainer = Color(getTertiaryContainer()),
            onTertiaryContainer = Color(getOnTertiaryContainer()),
            background = Color(getBackground()),
            onBackground = Color(getOnBackground()),
            surface = Color(getSurface()),
            onSurface = Color(getOnSurface()),
            surfaceVariant = Color(getSurfaceVariant()),
            onSurfaceVariant = Color(getOnSurfaceVariant()),
            surfaceTint = Color(getSurfaceTint()),
            inverseSurface = Color(getInverseSurface()),
            inverseOnSurface = Color(getInverseOnSurface()),
            error = Color(getError()),
            onError = Color(getOnError()),
            errorContainer = Color(getErrorContainer()),
            onErrorContainer = Color(getOnErrorContainer()),
            outline = Color(getOutline()),
            outlineVariant = Color(getOutlineVariant()),
            scrim = Color(getScrim()),
            surfaceBright = Color(getSurfaceBright()),
            surfaceDim = Color(getSurfaceDim()),
            surfaceContainer = Color(getSurfaceContainer()),
            surfaceContainerHigh = Color(getSurfaceContainerHigh()),
            surfaceContainerHighest = Color(getSurfaceContainerHighest()),
            surfaceContainerLow = Color(getSurfaceContainerLow()),
            surfaceContainerLowest = Color(getSurfaceContainerLowest()),
            primaryFixed = Color(getPrimaryFixed()),
            primaryFixedDim = Color(getPrimaryFixedDim()),
            onPrimaryFixed = Color(getOnPrimaryFixed()),
            onPrimaryFixedVariant = Color(getOnPrimaryFixedVariant()),
            secondaryFixed = Color(getSecondaryFixed()),
            secondaryFixedDim = Color(getSecondaryFixedDim()),
            onSecondaryFixed = Color(getOnSecondaryFixed()),
            onSecondaryFixedVariant = Color(getOnSecondaryFixedVariant()),
            tertiaryFixed = Color(getTertiaryFixed()),
            tertiaryFixedDim = Color(getTertiaryFixedDim()),
            onTertiaryFixed = Color(getOnTertiaryFixed()),
            onTertiaryFixedVariant = Color(getOnTertiaryFixedVariant()),
        )
    }
}
